FROM node as build
WORKDIR /quotes
COPY package.json .
RUN npm i
COPY . .
EXPOSE 3000
RUN npm run build

FROM nginx:stable-alpine
COPY --from=build /quotes/build /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
